DEPLOYMENT_ID = '62db02606a1219714a8eed4a'
API_KEY = 'NjJjZjIxNWQ1ZjgzMTI1YWEwZjBhZjViOmI5MXNHbnN0c1c4L25rZWNKOW1ZOVFXNWtxUUR6am1yK0NzNkFvQ2EvQnM9'
DATAROBOT_KEY = '544ec55f-61bf-f6ee-0caf-15c7f919a45d'
